### ISSUE TITLE
v1.2.2 build error using vcpkg port (VS 2022, 17.8.0)

### ISSUE THREAD

**Issue by nickdademo** [jeremy-rifkin/libassert#73]
`cpptrace` build fails.

See log file below:

```
Change Dir: 'C:/vcpkg/cpptrace/x64-windows-dbg'

Run Build Command(s): C:/Users/Nick/Documents/Projects/project/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v -v -j17 install
[1/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\symbols\symbols_with_dl.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\symbols\symbols_with_dl.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
[2/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\demangle\demangle_with_nothing.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\demangle\demangle_with_nothing.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
[3/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\symbols\symbols_with_addr2line.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\symbols\symbols_with_addr2line.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
[4/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\symbols\symbols_with_nothing.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\symbols\symbols_with_nothing.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
[5/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\symbols\symbols_with_libbacktrace.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\symbols\symbols_with_libbacktrace.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
[6/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\unwind\unwind_with_execinfo.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\unwind\unwind_with_execinfo.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
[7/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\unwind\unwind_with_winapi.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\unwind\unwind_with_winapi.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
[8/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\demangle\demangle_with_cxxabi.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\demangle\demangle_with_cxxabi.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
[9/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\unwind\unwind_with_unwind.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\unwind\unwind_with_unwind.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
[10/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\unwind\unwind_with_nothing.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\unwind\unwind_with_nothing.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
[11/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\symbols\symbols_with_libdwarf.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\symbols\symbols_with_libdwarf.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
[12/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\unwind\unwind_with_libunwind.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\unwind\unwind_with_libunwind.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
[13/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\demangle\demangle_with_winapi.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\demangle\demangle_with_winapi.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
[14/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\unwind\unwind_with_dbghelp.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\unwind\unwind_with_dbghelp.cpp
FAILED: CMakeFiles/cpptrace-lib.dir/src/unwind/unwind_with_dbghelp.cpp.obj 
C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\unwind\unwind_with_dbghelp.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\unwind\unwind_with_dbghelp.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\unwind\../utils/utils.hpp(422): error C2794: 'type': is not a member of any direct or indirect base class of 'std::enable_if<false,int>'
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\unwind\../utils/utils.hpp(368): error C2065: 'D': undeclared identifier
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\unwind\../utils/utils.hpp(368): error C2672: 'std::declval': no matching overloaded function found
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\type_traits(131): note: could be '_Add_reference<_Ty,void>::_Rvalue std::declval(void) noexcept'
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\unwind\../utils/utils.hpp(368): note: 'std::declval': invalid template argument for '_Ty', type expected
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\unwind\../utils/utils.hpp(368): error C2065: 'T': undeclared identifier
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\unwind\../utils/utils.hpp(368): error C2672: 'std::declval': no matching overloaded function found
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\type_traits(131): note: could be '_Add_reference<_Ty,void>::_Rvalue std::declval(void) noexcept'
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\unwind\../utils/utils.hpp(368): note: 'std::declval': invalid template argument for '_Ty', type expected
[15/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\symbols\symbols_core.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\symbols\symbols_core.cpp
FAILED: CMakeFiles/cpptrace-lib.dir/src/symbols/symbols_core.cpp.obj 
C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\symbols\symbols_core.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\symbols\symbols_core.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(422): error C2794: 'type': is not a member of any direct or indirect base class of 'std::enable_if<false,int>'
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): error C2065: 'D': undeclared identifier
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): error C2672: 'std::declval': no matching overloaded function found
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\type_traits(131): note: could be '_Add_reference<_Ty,void>::_Rvalue std::declval(void) noexcept'
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): note: 'std::declval': invalid template argument for '_Ty', type expected
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): error C2065: 'T': undeclared identifier
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): error C2672: 'std::declval': no matching overloaded function found
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\type_traits(131): note: could be '_Add_reference<_Ty,void>::_Rvalue std::declval(void) noexcept'
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): note: 'std::declval': invalid template argument for '_Ty', type expected
[16/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\cpptrace.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\cpptrace.cpp
FAILED: CMakeFiles/cpptrace-lib.dir/src/cpptrace.cpp.obj 
C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\cpptrace.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\cpptrace.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(422): error C2794: 'type': is not a member of any direct or indirect base class of 'std::enable_if<false,int>'
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): error C2065: 'D': undeclared identifier
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): error C2672: 'std::declval': no matching overloaded function found
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\type_traits(131): note: could be '_Add_reference<_Ty,void>::_Rvalue std::declval(void) noexcept'
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): note: 'std::declval': invalid template argument for '_Ty', type expected
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): error C2065: 'T': undeclared identifier
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): error C2672: 'std::declval': no matching overloaded function found
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\type_traits(131): note: could be '_Add_reference<_Ty,void>::_Rvalue std::declval(void) noexcept'
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): note: 'std::declval': invalid template argument for '_Ty', type expected
[17/19] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\symbols\symbols_with_dbghelp.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\symbols\symbols_with_dbghelp.cpp
FAILED: CMakeFiles/cpptrace-lib.dir/src/symbols/symbols_with_dbghelp.cpp.obj 
C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe   /TP -DCPPTRACE_DEMANGLE_WITH_WINAPI -DCPPTRACE_GET_SYMBOLS_WITH_DBGHELP -DCPPTRACE_UNWIND_WITH_DBGHELP -Dcpptrace_lib_EXPORTS -IC:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\include -external:IC:\vcpkg\cpptrace\x64-windows-dbg\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /W4 /WX /permissive- /showIncludes /FoCMakeFiles\cpptrace-lib.dir\src\symbols\symbols_with_dbghelp.cpp.obj /FdCMakeFiles\cpptrace-lib.dir\ /FS -c C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\symbols\symbols_with_dbghelp.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(422): error C2794: 'type': is not a member of any direct or indirect base class of 'std::enable_if<false,int>'
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): error C2065: 'D': undeclared identifier
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): error C2672: 'std::declval': no matching overloaded function found
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\type_traits(131): note: could be '_Add_reference<_Ty,void>::_Rvalue std::declval(void) noexcept'
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): note: 'std::declval': invalid template argument for '_Ty', type expected
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): error C2065: 'T': undeclared identifier
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): error C2672: 'std::declval': no matching overloaded function found
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\type_traits(131): note: could be '_Add_reference<_Ty,void>::_Rvalue std::declval(void) noexcept'
C:\vcpkg\cpptrace\src\v0.3.0-3f6edebffe.clean\src\binary\../utils/utils.hpp(368): note: 'std::declval': invalid template argument for '_Ty', type expected
ninja: build stopped: subcommand failed.

```

**Comment by jeremy-rifkin** [comment]
Hi @nickdademo, what version of msvc do you have and what vcpkg commit are you on?

**Comment by nickdademo** [comment]
@jeremy-rifkin 

VS: 17.8.2
vcpkg commit: `4cac260c4b7331538d31886f57739fea0bffa27e`

**Comment by nickdademo** [comment]
> Hi @nickdademo, I've added a workaround upstream and libassert builds on msvc 19.38 should work as of [b672ba2](https://github.com/jeremy-rifkin/libassert/commit/b672ba234858a819a735eb4c18a708aed12e446c)

Works via vcpkg now - thanks a lot!
